CREATE TABLE [dbo].[BLOG]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(128) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[BuiltIn] BIT NOT NULL,

	[UserId] UNIQUEIDENTIFIER NULL,
	[CategoryId] UNIQUEIDENTIFIER NOT NULL,
)
