CREATE TABLE [dbo].[EVENT]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Theme] NVARCHAR(MAX) NOT NULL,
	[Start] DATETIME NOT NULL,
	[End] DATETIME NOT NULL,
	[Address] NVARCHAR(MAX) NULL,
	[City] NVARCHAR(MAX) NOT NULL,
	[Zipcode] NVARCHAR(MAX) NULL,
	[Gps] NVARCHAR(MAX) NULL,
	[Facebook] NVARCHAR(MAX) NULL,
	[Description] NVARCHAR(MAX) NULL,
	[ShowPrize] BIT NOT NULL,
	[PrizeMember] SMALLINT NULL,
	[PrizeNomember] SMALLINT NULL,
	[Currency] INT NOT NULL,
	[EnableRegistration] BIT NOT NULL,
	[RegistrationDeadline] DATETIME NULL,
	[CurrentParticipiants] INT NOT NULL,
	[MaximumParticipiants] INT NULL,
	[Prepayment] SMALLINT NULL,
	[PrepaymentDeadline] DATETIME NULL,
	[AccountNumber] NVARCHAR(MAX) NULL,
	[Discriminator] NVARCHAR(MAX) NOT NULL,

	[CountryId] UNIQUEIDENTIFIER NULL,
)
