CREATE TABLE [dbo].[PRODUCT]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[Url] NVARCHAR(MAX) NULL,
	[Description] NVARCHAR(MAX) NULL,
	[Prize] INT NULL,
	[ShowPrize] BIT NOT NULL,
	[Currency] INT NOT NULL,

	[CategoryId] UNIQUEIDENTIFIER NOT NULL,
)
