CREATE TABLE [dbo].[Training]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Day] INT NOT NULL,
	[ForChildren] BIT NOT NULL,
	[Start] DATETIME NOT NULL,
	[End] DATETIME NOT NULL,
	[Address] NVARCHAR(MAX) NULL,
	[City] NVARCHAR(64) NOT NULL,
	[Zipcode] NVARCHAR(16) NULL,
	[Gps] NVARCHAR(64) NULL,
	[Description] NVARCHAR(MAX) NULL,

	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[CountryId] UNIQUEIDENTIFIER NULL
)
