CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[BujinkanTitle] INT NOT NULL,
	[FirstName] NVARCHAR(64) NOT NULL,
	[Surname] NVARCHAR(64) NOT NULL,
	[Email] NVARCHAR(64) NOT NULL,
	[Password] NVARCHAR(128) NOT NULL,
	[Web] NVARCHAR(MAX) NULL,
	[Facebook] NVARCHAR(MAX) NULL,
	[Phone] NVARCHAR(32) NULL,
	[Dan] SMALLINT NULL,
	[Order] INT NOT NULL,
	[Description] NVARCHAR(MAX) NULL,

	[RoleId] UNIQUEIDENTIFIER NOT NULL,
	[CountryId] UNIQUEIDENTIFIER NULL,
	[DojoId] UNIQUEIDENTIFIER NULL
)
