CREATE TABLE [dbo].[USER]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[BujinkanTitle] INT NOT NULL,
	[FirstName] NVARCHAR(MAX) NOT NULL,
	[Surname] NVARCHAR(MAX) NOT NULL,
	[Email] NVARCHAR(MAX) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	[Web] NVARCHAR(MAX) NULL,
	[Facebook] NVARCHAR(MAX) NULL,
	[Phone] NVARCHAR(MAX) NULL,
	[Dan] SMALLINT NULL,
	[Order] INT NOT NULL,
	[Description] NVARCHAR(MAX) NULL,

	[RoleId] UNIQUEIDENTIFIER NOT NULL,
	[CountryId] UNIQUEIDENTIFIER NULL,
	[DojoId] UNIQUEIDENTIFIER NULL
)
