CREATE TABLE [dbo].[ACTUALITY]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UpdatedDate] DATETIME NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[Url] NVARCHAR(MAX) NULL,
	[Date] DATETIME NULL,
	[UserDefinableId] UNIQUEIDENTIFIER NULL,
)
