CREATE TABLE [dbo].[VOCABULARY]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[UpdatedDate] DATETIME NOT NULL,
	[Word] NVARCHAR(128) NOT NULL,
	[Translate] NVARCHAR(MAX) NOT NULL,
)
