/* Training */
ALTER TABLE [dbo].[TRAINING] ADD CONSTRAINT [FK_Training_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USER] (Id)
GO
ALTER TABLE [dbo].[TRAINING] ADD CONSTRAINT [FK_Training_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[COUNTRY] (Id)
GO
ALTER TABLE [dbo].[TRAINING] ADD  CONSTRAINT [FK_Training_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* User */
ALTER TABLE [dbo].[USER] ADD CONSTRAINT [FK_User_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[COUNTRY] (Id)
GO
ALTER TABLE [dbo].[USER] ADD CONSTRAINT [FK_User_Dojo] FOREIGN KEY ([DojoId]) REFERENCES [dbo].[DOJO] (Id)
GO
ALTER TABLE [dbo].[USER] ADD CONSTRAINT [FK_User_Role] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[ROLE] (Id)
GO
ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [FK_User_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* Event */
ALTER TABLE [dbo].[EVENT] ADD CONSTRAINT [FK_Event_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[COUNTRY] (Id)
GO
ALTER TABLE [dbo].[EVENT] ADD  CONSTRAINT [FK_Event_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* Blog */
ALTER TABLE [dbo].[BLOG] ADD CONSTRAINT [FK_Blog_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USER] (Id)
GO
ALTER TABLE [dbo].[BLOG] ADD CONSTRAINT [FK_Blog_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[CATEGORY] (Id)
GO
ALTER TABLE [dbo].[BLOG] ADD  CONSTRAINT [FK_Blog_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* Product */
ALTER TABLE [dbo].[PRODUCT] ADD CONSTRAINT [FK_Product_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[CATEGORY] (Id)
GO
ALTER TABLE [dbo].[PRODUCT] ADD  CONSTRAINT [FK_Product_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* Menu Item */
ALTER TABLE [dbo].[MENU_ITEM] ADD CONSTRAINT [FK_MenuItem_ParentMenuItem] FOREIGN KEY ([ParentMenuItemId]) REFERENCES [dbo].[MENU_ITEM] (Id)
GO
ALTER TABLE [dbo].[MENU_ITEM] ADD CONSTRAINT [FK_MenuItem_UserDefinable] FOREIGN KEY ([UserDefinableId]) REFERENCES [dbo].[USER_DEFINABLE] (Id)
GO
ALTER TABLE [dbo].[MENU_ITEM] ADD CONSTRAINT [FK_MenuItem_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[CATEGORY] (Id)
GO

/* Gallery */
ALTER TABLE [dbo].[GALLERY] ADD CONSTRAINT [FK_Gallery_CoverPhoto] FOREIGN KEY ([CoverPhotoId]) REFERENCES [dbo].[RESOURCE] (Id)
GO
ALTER TABLE [dbo].[GALLERY] ADD  CONSTRAINT [FK_Gallery_UserDefinable_Inheritence] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO
ALTER TABLE [dbo].[GALLERY] ADD  CONSTRAINT [FK_Gallery_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* Join_UserEvent */
ALTER TABLE [dbo].[JOIN_USER_EVENT] ADD CONSTRAINT [FK_Join_UserEvent_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USER] (Id) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[JOIN_USER_EVENT] ADD CONSTRAINT [FK_Join_UserEvent_Event] FOREIGN KEY ([EventId]) REFERENCES [dbo].[EVENT] (Id) ON DELETE CASCADE
GO

/* Entry */
ALTER TABLE [dbo].[ENTRY] ADD CONSTRAINT [FK_Entry_Event] FOREIGN KEY ([EventId]) REFERENCES [dbo].[EVENT] (Id)
GO

/* UserDefinable */
ALTER TABLE [dbo].[USER_DEFINABLE] ADD CONSTRAINT [FK_UserDefinable_User] FOREIGN KEY ([UserCreatorId]) REFERENCES [dbo].[USER] (Id)
GO

/* Actuality */
ALTER TABLE [dbo].[ACTUALITY] ADD CONSTRAINT [FK_Actuality_UserDefinable] FOREIGN KEY ([UserDefinableId]) REFERENCES [dbo].[USER_DEFINABLE] (Id)
GO

/* Link */
ALTER TABLE [dbo].[LINK] ADD CONSTRAINT [FK_Link_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[CATEGORY] (Id)
GO

/* Category */
ALTER TABLE [dbo].[CATEGORY] ADD  CONSTRAINT [FK_Category_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO