ALTER TABLE [dbo].[User] ADD CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Training] ADD CONSTRAINT [PK_Training] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Country] ADD CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Dojo] ADD CONSTRAINT [PK_Dojo] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Role] ADD CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Vocabulary] ADD CONSTRAINT [PK_Vocabulary] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Question] ADD CONSTRAINT [PK_Question] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Link] ADD CONSTRAINT [PK_Link] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Event] ADD CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Category] ADD CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Blog] ADD CONSTRAINT [PK_Blog] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Product] ADD CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[MenuItem] ADD CONSTRAINT [PK_MenuItem] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Resource] ADD CONSTRAINT [PK_Resource] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Actuality] ADD CONSTRAINT [PK_Actuality] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Gallery] ADD CONSTRAINT [PK_Gallery] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[Join_UserEvent] ADD CONSTRAINT [PK_Join_UserEvent] PRIMARY KEY CLUSTERED ([EventId] ASC, [UserId] ASC)
GO
ALTER TABLE [dbo].[Entry] ADD CONSTRAINT [PK_Entry] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[UserDefinable] ADD CONSTRAINT [PK_UserDefinable] PRIMARY KEY CLUSTERED ([Id] ASC)
GO