ALTER TABLE [dbo].[USER] ADD CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[TRAINING] ADD CONSTRAINT [PK_Training] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[COUNTRY] ADD CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[DOJO] ADD CONSTRAINT [PK_Dojo] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[ROLE] ADD CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[VOCABULARY] ADD CONSTRAINT [PK_Vocabulary] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[QUESTION] ADD CONSTRAINT [PK_Question] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[LINK] ADD CONSTRAINT [PK_Link] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[EVENT] ADD CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[CATEGORY] ADD CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[BLOG] ADD CONSTRAINT [PK_Blog] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[PRODUCT] ADD CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[MENU_ITEM] ADD CONSTRAINT [PK_MenuItem] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[RESOURCE] ADD CONSTRAINT [PK_Resource] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[ACTUALITY] ADD CONSTRAINT [PK_Actuality] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[GALLERY] ADD CONSTRAINT [PK_Gallery] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[JOIN_USER_EVENT] ADD CONSTRAINT [PK_Join_UserEvent] PRIMARY KEY CLUSTERED ([EventId] ASC, [UserId] ASC)
GO
ALTER TABLE [dbo].[ENTRY] ADD CONSTRAINT [PK_Entry] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[USER_DEFINABLE] ADD CONSTRAINT [PK_UserDefinable] PRIMARY KEY CLUSTERED ([Id] ASC)
GO