//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.I18n.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.I18n.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo účtu.
        /// </summary>
        public static string label_account_number {
            get {
                return ResourceManager.GetString("label_account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidání.
        /// </summary>
        public static string label_add {
            get {
                return ResourceManager.GetString("label_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat kategorii.
        /// </summary>
        public static string label_add_category {
            get {
                return ResourceManager.GetString("label_add_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat odkaz.
        /// </summary>
        public static string label_add_link {
            get {
                return ResourceManager.GetString("label_add_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat otázku.
        /// </summary>
        public static string label_add_question {
            get {
                return ResourceManager.GetString("label_add_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat překlad.
        /// </summary>
        public static string label_add_vocabulary {
            get {
                return ResourceManager.GetString("label_add_vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string label_address {
            get {
                return ResourceManager.GetString("label_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace.
        /// </summary>
        public static string label_administration {
            get {
                return ResourceManager.GetString("label_administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace Bujinkan Czech Dojo.
        /// </summary>
        public static string label_administration_of_bcd {
            get {
                return ResourceManager.GetString("label_administration_of_bcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dle domluvy.
        /// </summary>
        public static string label_agreement {
            get {
                return ResourceManager.GetString("label_agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpověď.
        /// </summary>
        public static string label_answer {
            get {
                return ResourceManager.GetString("label_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Články.
        /// </summary>
        public static string label_articles {
            get {
                return ResourceManager.GetString("label_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string label_blog {
            get {
                return ResourceManager.GetString("label_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string label_blog_categories {
            get {
                return ResourceManager.GetString("label_blog_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string label_blog_category {
            get {
                return ResourceManager.GetString("label_blog_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string label_blogs {
            get {
                return ResourceManager.GetString("label_blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-In.
        /// </summary>
        public static string label_builtin {
            get {
                return ResourceManager.GetString("label_builtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string label_category {
            get {
                return ResourceManager.GetString("label_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string label_city {
            get {
                return ResourceManager.GetString("label_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace.
        /// </summary>
        public static string label_civic_association_registration {
            get {
                return ResourceManager.GetString("label_civic_association_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string label_close {
            get {
                return ResourceManager.GetString("label_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení.
        /// </summary>
        public static string label_confirmation {
            get {
                return ResourceManager.GetString("label_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        public static string label_continue {
            get {
                return ResourceManager.GetString("label_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Země.
        /// </summary>
        public static string label_country {
            get {
                return ResourceManager.GetString("label_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace dat.
        /// </summary>
        public static string label_create_update_delete_all {
            get {
                return ResourceManager.GetString("label_create_update_delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string label_currency {
            get {
                return ResourceManager.GetString("label_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální počet účastníků.
        /// </summary>
        public static string label_current_participiants {
            get {
                return ResourceManager.GetString("label_current_participiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kč.
        /// </summary>
        public static string label_czk {
            get {
                return ResourceManager.GetString("label_czk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dan.
        /// </summary>
        public static string label_dan {
            get {
                return ResourceManager.GetString("label_dan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string label_date {
            get {
                return ResourceManager.GetString("label_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den.
        /// </summary>
        public static string label_day {
            get {
                return ResourceManager.GetString("label_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dojo.
        /// </summary>
        public static string label_dojo {
            get {
                return ResourceManager.GetString("label_dojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace dojo.
        /// </summary>
        public static string label_dojo_creation {
            get {
                return ResourceManager.GetString("label_dojo_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string label_email {
            get {
                return ResourceManager.GetString("label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolit registraci.
        /// </summary>
        public static string label_enable_registration {
            get {
                return ResourceManager.GetString("label_enable_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        public static string label_end {
            get {
                return ResourceManager.GetString("label_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        public static string label_euro {
            get {
                return ResourceManager.GetString("label_euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Událost.
        /// </summary>
        public static string label_event {
            get {
                return ResourceManager.GetString("label_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Události.
        /// </summary>
        public static string label_events {
            get {
                return ResourceManager.GetString("label_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string label_facebook {
            get {
                return ResourceManager.GetString("label_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplnit formulář.
        /// </summary>
        public static string label_fill_form {
            get {
                return ResourceManager.GetString("label_fill_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string label_firstname {
            get {
                return ResourceManager.GetString("label_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Určeno pro děti.
        /// </summary>
        public static string label_for_children {
            get {
                return ResourceManager.GetString("label_for_children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pátek.
        /// </summary>
        public static string label_friday {
            get {
                return ResourceManager.GetString("label_friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galerie.
        /// </summary>
        public static string label_galleries {
            get {
                return ResourceManager.GetString("label_galleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galerie.
        /// </summary>
        public static string label_gallery {
            get {
                return ResourceManager.GetString("label_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string label_gps {
            get {
                return ResourceManager.GetString("label_gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        public static string label_home {
            get {
                return ResourceManager.GetString("label_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ.
        /// </summary>
        public static string label_ic {
            get {
                return ResourceManager.GetString("label_ic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace.
        /// </summary>
        public static string label_information {
            get {
                return ResourceManager.GetString("label_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruktor.
        /// </summary>
        public static string label_instructor {
            get {
                return ResourceManager.GetString("label_instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPY.
        /// </summary>
        public static string label_jpy {
            get {
                return ResourceManager.GetString("label_jpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odkaz.
        /// </summary>
        public static string label_link {
            get {
                return ResourceManager.GetString("label_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odkazy.
        /// </summary>
        public static string label_links {
            get {
                return ResourceManager.GetString("label_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam.
        /// </summary>
        public static string label_list {
            get {
                return ResourceManager.GetString("label_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum počtu účastníků.
        /// </summary>
        public static string label_maximum_participiants {
            get {
                return ResourceManager.GetString("label_maximum_participiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string label_menu {
            get {
                return ResourceManager.GetString("label_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace menu.
        /// </summary>
        public static string label_menu_creation {
            get {
                return ResourceManager.GetString("label_menu_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pondělí.
        /// </summary>
        public static string label_monday {
            get {
                return ResourceManager.GetString("label_monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string label_name {
            get {
                return ResourceManager.GetString("label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový.
        /// </summary>
        public static string label_new {
            get {
                return ResourceManager.GetString("label_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string label_no {
            get {
                return ResourceManager.GetString("label_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizace.
        /// </summary>
        public static string label_organization {
            get {
                return ResourceManager.GetString("label_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ organizace.
        /// </summary>
        public static string label_organization_type {
            get {
                return ResourceManager.GetString("label_organization_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string label_password {
            get {
                return ResourceManager.GetString("label_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string label_phone {
            get {
                return ResourceManager.GetString("label_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záloha.
        /// </summary>
        public static string label_prepayment {
            get {
                return ResourceManager.GetString("label_prepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum poslání zálohy.
        /// </summary>
        public static string label_prepayment_deadline {
            get {
                return ResourceManager.GetString("label_prepayment_deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena (člen).
        /// </summary>
        public static string label_prize_member {
            get {
                return ResourceManager.GetString("label_prize_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena (nečlen).
        /// </summary>
        public static string label_prize_nomember {
            get {
                return ResourceManager.GetString("label_prize_nomember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string label_product_category {
            get {
                return ResourceManager.GetString("label_product_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty.
        /// </summary>
        public static string label_products {
            get {
                return ResourceManager.GetString("label_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka.
        /// </summary>
        public static string label_question {
            get {
                return ResourceManager.GetString("label_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázky.
        /// </summary>
        public static string label_questions {
            get {
                return ResourceManager.GetString("label_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum ukončení registrace.
        /// </summary>
        public static string label_registration_deadline {
            get {
                return ResourceManager.GetString("label_registration_deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_role {
            get {
                return ResourceManager.GetString("label_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace rolí.
        /// </summary>
        public static string label_role_creation {
            get {
                return ResourceManager.GetString("label_role_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_roles {
            get {
                return ResourceManager.GetString("label_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobota.
        /// </summary>
        public static string label_saturday {
            get {
                return ResourceManager.GetString("label_saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string label_save {
            get {
                return ResourceManager.GetString("label_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seminář.
        /// </summary>
        public static string label_seminar {
            get {
                return ResourceManager.GetString("label_seminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semináře.
        /// </summary>
        public static string label_seminars {
            get {
                return ResourceManager.GetString("label_seminars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        public static string label_settings {
            get {
                return ResourceManager.GetString("label_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shidoshi.
        /// </summary>
        public static string label_shidoshi {
            get {
                return ResourceManager.GetString("label_shidoshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shihan.
        /// </summary>
        public static string label_shihan {
            get {
                return ResourceManager.GetString("label_shihan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budoshop.
        /// </summary>
        public static string label_shop {
            get {
                return ResourceManager.GetString("label_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukázat cenu.
        /// </summary>
        public static string label_show_prize {
            get {
                return ResourceManager.GetString("label_show_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek.
        /// </summary>
        public static string label_start {
            get {
                return ResourceManager.GetString("label_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neděle.
        /// </summary>
        public static string label_sunday {
            get {
                return ResourceManager.GetString("label_sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string label_surname {
            get {
                return ResourceManager.GetString("label_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitel.
        /// </summary>
        public static string label_teacher {
            get {
                return ResourceManager.GetString("label_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitelé.
        /// </summary>
        public static string label_teachers {
            get {
                return ResourceManager.GetString("label_teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téma.
        /// </summary>
        public static string label_theme {
            get {
                return ResourceManager.GetString("label_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čtvrtek.
        /// </summary>
        public static string label_thursday {
            get {
                return ResourceManager.GetString("label_thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        public static string label_time {
            get {
                return ResourceManager.GetString("label_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        public static string label_time_end {
            get {
                return ResourceManager.GetString("label_time_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek.
        /// </summary>
        public static string label_time_start {
            get {
                return ResourceManager.GetString("label_time_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul.
        /// </summary>
        public static string label_title {
            get {
                return ResourceManager.GetString("label_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trénink.
        /// </summary>
        public static string label_training {
            get {
                return ResourceManager.GetString("label_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tréninky.
        /// </summary>
        public static string label_trainings {
            get {
                return ResourceManager.GetString("label_trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Překlad.
        /// </summary>
        public static string label_translate {
            get {
                return ResourceManager.GetString("label_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úterý.
        /// </summary>
        public static string label_tuesday {
            get {
                return ResourceManager.GetString("label_tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string label_usd {
            get {
                return ResourceManager.GetString("label_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace uživatelů.
        /// </summary>
        public static string label_user_creation {
            get {
                return ResourceManager.GetString("label_user_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string label_video {
            get {
                return ResourceManager.GetString("label_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhledy.
        /// </summary>
        public static string label_views {
            get {
                return ResourceManager.GetString("label_views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovník.
        /// </summary>
        public static string label_vocabulary {
            get {
                return ResourceManager.GetString("label_vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string label_web {
            get {
                return ResourceManager.GetString("label_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Středa.
        /// </summary>
        public static string label_wednesday {
            get {
                return ResourceManager.GetString("label_wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítejte.
        /// </summary>
        public static string label_welcome {
            get {
                return ResourceManager.GetString("label_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovo.
        /// </summary>
        public static string label_word {
            get {
                return ResourceManager.GetString("label_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string label_yes {
            get {
                return ResourceManager.GetString("label_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string label_zipcode {
            get {
                return ResourceManager.GetString("label_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; je neplatný e-mail.
        /// </summary>
        public static string validation_email_message {
            get {
                return ResourceManager.GetString("validation_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &apos;{0}&apos; musí být mezi &apos;{1}&apos; a &apos;{2}&apos;.
        /// </summary>
        public static string validation_range_message {
            get {
                return ResourceManager.GetString("validation_range_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &apos;{0}&apos; je povinná.
        /// </summary>
        public static string validation_required_message {
            get {
                return ResourceManager.GetString("validation_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; je neplatná url adresa.
        /// </summary>
        public static string validation_url_message {
            get {
                return ResourceManager.GetString("validation_url_message", resourceCulture);
            }
        }
    }
}
